# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: compile-manifest

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build-manifest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          wget https://raw.githubusercontent.com/bioimage-io/bioimage-io-models/master/requirements.txt
          python -m pip install --upgrade pip
          pip install -r requirements.txt     

      - name: Compile manifest file
        run: |
          wget https://raw.githubusercontent.com/bioimage-io/bioimage-io-models/master/src/compile_model_manifest.py
          python compile_model_manifest.py

      - name: Save build output
        uses: actions/upload-artifact@v1
        with:
          name: built-output
          path: ./

      - name: Verify config files
        run: |
          pip install git+https://github.com/bioimage-io/python-bioimage-io.git
          python -m pybio.spec verify-bioimageio-manifest manifest.bioimage.io.yaml
