name: test BioImage.IO resources  # for compatibility with DeepImageJ

concurrency: test-resources

on:
  workflow_dispatch:
    inputs:
      pending_matrix:
        description: 'json encoded gh matrix of pending validations for new or updated resources (default: test on all resources)'
        required: true
        default: '{"include": [{"resource_id": "**", "version_id": "**"}]}'
        type: string

jobs:
  // TODO automatize the version management
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        version: [2.1.13]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: bioimage-io/collection-bioimage-io
        ref: gh-pages
        path: bioimageio-gh-pages
    - name: Setup ilastik env
      uses: conda-incubator/setup-miniconda@v2
      with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          activate-environment: ilastik-env
          use-mamba: true
    - name: Download Fiji env
      run: wget --output-document env.yaml ${{ matrix.env_url }}
    - name: Download DeepImageJ and deps
      run: mamba env update -n ilastik-env -f env.yaml
    - name: test with DeepImageJ ${{matrix.v }}
      shell: bash -l {0}
      run: python scripts/test_many_with_ilastik.py dist '${{ github.event.inputs.pending_matrix }}' --postfix ${{ matrix.v }}
    - name: Upload test summaries
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.v }}
        path: dist
        retention-days: 1

  deploy:
    needs: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        path: artifacts
    - name: merge ilastik test summaries  # (they differ by postfix)
      run: |
        mkdir dist
        cp -r artifacts/*/* dist
    - name: Deploy test summaries to gh-pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        clean: false
        branch: gh-pages
        folder: dist
