name: test BioImage.IO resources  # for compatibility with DeepImageJ

concurrency: test-resources

on:
  workflow_dispatch:
    inputs:
      pending_matrix:
        description: 'json encoded gh matrix of pending validations for new or updated resources (default: test on all resources)'
        required: true
        default: '{"include": [{"resource_id": "**", "version_id": "**"}]}'
        type: string

jobs:
  # TODO automatize the version management
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        v: [2.1.13]

    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '8'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: bioimage-io/collection-bioimage-io
        ref: gh-pages
        path: bioimageio-gh-pages
    - name: Setup conda env and install deps
      uses: conda-incubator/setup-miniconda@v2
      with:
          python-version: 3.8
          activate-environment: deepImageJEnv
          environment-file: environment-test.yaml
          miniconda-version: "latest"
    - name: Download Fiji env
      run: |
        wget https://downloads.imagej.net/fiji/archive/20201104-1356/fiji-linux64.zip
        unzip fiji-linux64.zip -d $HOME
        ls
        echo $HOME
        # fix FilamentDetector issue
        mv $HOME/Fiji.app/jars/FilamentDetector-1.0.0.jar $HOME/Fiji.app/jars/FilamentDetector-1.0.0.jar.disabled

        rm $HOME/Fiji.app/jars/jna-4*.jar
    - name: Download DeepImageJ and deps
      run: |
        wget https://github.com/deepimagej/deepimagej-plugin/releases/download/2.1.12/dependencies_2112.zip
        unzip dependencies_2112.zip
        mv dependencies_2112/dependencies_2.1.12/* $HOME/Fiji.app/jars/

        wget https://github.com/deepimagej/deepimagej-plugin/releases/download/2.1.12/DeepImageJ_-2.1.12.jar
        mv DeepImageJ_-2.1.12.jar $HOME/Fiji.app/plugins/DeepImageJ_-2.1.12.jar
    - name: Install BioImage.io Core
      shell: bash -l {0}
      run: |
        conda install -c conda-forge bioimageio.core
    - name: test with DeepImageJ ${{matrix.v }}
      shell: bash -l {0}
      run: |
        python scripts/test_many_with_deepimagej.py dist '${{ github.event.inputs.pending_matrix }}' $HOME/Fiji.app --postfix ${{ matrix.v }}
    - name: Upload test summaries
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.v }}
        path: dist
        retention-days: 1

  deploy:
    needs: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        path: artifacts
    - name: merge deepimagej test summaries  # (they differ by postfix)
      run: |
        mkdir dist
        cp -r artifacts/*/* dist
    - name: Deploy test summaries to gh-pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        clean: false
        branch: gh-pages
        folder: dist
