name: test BioImage.IO resources  # for compatibility with DeepImageJ

concurrency: test-resources

on:
  workflow_dispatch:
    inputs:
      pending_matrix:
        description: 'json encoded gh matrix of pending validations for new or updated resources (default: test on all resources)'
        required: true
        default: '{"include": [{"resource_id": "**", "version_id": "**"}]}'
        type: string

jobs:
  // TODO automatize the version management
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        version: [2.1.13]

    steps:
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '8'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
        repository: bioimage-io/collection-bioimage-io
        ref: gh-pages
        path: bioimageio-gh-pages
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Python dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment-test.yaml --name deepImageJEnv
    - name: Download Fiji env
      run: |
        wget https://downloads.imagej.net/fiji/archive/20201104-1356/fiji-linux64.zip
        unzip fiji-linux64.zip -d $pwd
        ls
        echo $pwd
        # fix FilamentDetector issue
        mv $pwd/Fiji.app/jars/FilamentDetector-1.0.0.jar $pwd/Fiji.app/jars/FilamentDetector-1.0.0.jar.disabled

        rm $pwd/Fiji.app/jars/jna-4*.jar
    - name: Download DeepImageJ and deps
      run: |
        wget https://github.com/deepimagej/deepimagej-plugin/releases/download/2.1.12/dependencies_2112.zip
        unzip dependencies_2112.zip
        mv dependencies_2112/dependencies_2.1.12/* $HOME/Fiji.app/jars/

        wget https://github.com/deepimagej/models/releases/download/0.3/DeepImageJ_-2.1.12.jar
        rm $pwd/Fiji.app/plugins/DeepImageJ*.jar
        mv DeepImageJ_-2.1.12.jar $pwd/Fiji.app/plugins/DeepImageJ_-2.1.12.jar
    - name: test with DeepImageJ ${{matrix.v }}
      run: |
        $CONDA/bin/conda activate deepImageJEnv
        echo $pwd/Fiji.app
        python scripts/test_many_with_deepimagej.py dist '${{ github.event.inputs.pending_matrix }}' \
            --fiji_path $pwd/Fiji.app --postfix ${{ matrix.v }}
    - name: Upload test summaries
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.v }}
        path: dist
        retention-days: 1

  deploy:
    needs: run
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        path: artifacts
    - name: merge ilastik test summaries  # (they differ by postfix)
      run: |
        mkdir dist
        cp -r artifacts/*/* dist
    - name: Deploy test summaries to gh-pages 🚀
      uses: JamesIves/github-pages-deploy-action@v4.2.3
      with:
        clean: false
        branch: gh-pages
        folder: dist
