name: validate collection

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    

jobs:
  validate-collection:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install bioimageio.spec
        run: pip install bioimageio.spec
      - name: validate collection
        run: bioimageio validate manifest.bioimage.io.yaml
